### ISSUE TITLE
crash when clicking Apoapsis button to set maneuver location

### ISSUE THREAD

**Issue by ghost** [radistmorse/KSPPreciseManeuver#1]
This is pre-release build 1203, x64 on Windows.

My process for getting into orbit is pretty straightforward:
- launch
- while coasting to apoapsis, set a maneuver node
- click on the orbit line, then click AP to position it exactly at apoapsis

Crashes right then.  It works sometimes though, more often than not.

I haven't experienced any crashing while setting maneuver nodes without the  mod window controls.

Hope it helps, here is the crash data and my save in case.  Thanks for the mod!  It's awesome.

https://gist.github.com/gnivler/b0794a5f845084c85401dfd9d5008c3e

GitHub claims it can support zip attachments!  This is a lie!

Here's a link to the crash data, sorry.

http://s000.tinyupload.com/index.php?file_id=03872177568533666343

**Comment by radistmorse** [comment]
Yes, KSP sometimes returns NaNs instead of valid parameters, it never did it on getTimeToAP before, though. I should sanitize input better.

**Comment by radistmorse** [comment]
The new release checks for NaNs whenever possible. Should be fixed now.

**Comment by ghost** [comment]
Just crashed again, hope the log helps:

[output_log.txt](https://github.com/radistmorse/KSPPreciseManeuver/files/222850/output_log.txt)

FWIW it seems like clicking Ap quickly after bringing up the map is more likely to crash.. at least with the previous version you released.  This is the first crash with the latest.
