### ISSUE TITLE
Editing maneuver node values crashes the game

### ISSUE THREAD

**Issue by mullinger** [radistmorse/KSPPreciseManeuver#17]
Hi,

when I tried to manually edit the maveuver node prograde value the game crashed.

Steam version -> Most recent version of KSP
A few other (compatible) mods installed, all through CKAN.

**Comment by radistmorse** [comment]
Please, provide your logfile.

**Comment by mullinger** [comment]
There are no logfiles. 
I even searched where I would expect the crash-/logfiles . Nothing. Just a suddenly exiting game :-/

**Comment by theonegalen** [comment]
Try ksp.log in the main KSP folder.

**Comment by mullinger** [comment]
There is no ksp.log... Thats what I am saying. Nothing.

I can't reproduce the reported bug though. The game is unreliably crashing pretty often with only 2 mods installed, but the issue here does not seem the cause.
Closing for now.
