### ISSUE TITLE
triggered staging locked / unusable (game breaking)

### ISSUE THREAD

**Issue by ghost** [radistmorse/KSPPreciseManeuver#2]
Noticed this problems while having several mods installed so I troubleshooted it by going stock, the problem went away, then added only this mod and trouble came back.

If you load this game and pick the suborbital ship piloted by Jeb (I think), it's coming up near apo.  The staging light is green at first but if you toggle to map and back it goes purple, locked.  ALT-L doesn't correct it.  Manual right-click part controls can separate and start the engines.  If you switch crafts, I've seen it go green but it definitely prefers being purple.

Thanks again - love your work.

Save folder:
http://s000.tinyupload.com/index.php?file_id=05103657280585709198

**Comment by gnivler** [comment]
I'm no longer convinced this problem has anything to do with this mod... weird stuff happening.  I'm blowing away 'suspicious' craft and retesting.

**Comment by ghost** [comment]
I got the locked staging effect while at the launchpad, just toggled to map and back and then can't stage.

Not sure what log is available that I can provide, just let me know...

**Comment by ghost** [comment]
I just had this happen without the mod installed.  It happened 100% of the time with it though.  Stock bug fixing might help...

**Comment by radistmorse** [comment]
The mod has nothing to do with staging. It's not even active unless you go to the map view. I'm closing it, since it's clearly not an issue of this mod.
