### ISSUE TITLE
i fixed the incompatibility. Is it possible for me to commit?

### ISSUE THREAD

**Issue by dsula** [radistmorse/KSPPreciseManeuver#21]

**Comment by gater308** [comment]
Do you mean that you fixed the compatibility with 1.6? It looks like you can as long as the original copyright stays in place.

**Comment by dsula** [comment]
Yes,

I'll try to fork the project and deploy the fix. Not sure how to do 
that, never done it before. So hold on tight.

Cheer
daniel

**Comment by radistmorse** [comment]
fixed
