### ISSUE TITLE
Incompatible with KSP 1.6

### ISSUE THREAD

**Issue by gater308** [radistmorse/KSPPreciseManeuver#22]
Crashes game. not sure how to fix

**Comment by radistmorse** [comment]
What exactly crashed? Can you provide some logs.

**Comment by gater308** [comment]
![preciseguidance](https://user-images.githubusercontent.com/49091113/55283010-9a0a4780-531e-11e9-94c7-5fe194086b38.png)
[KSP.log](https://github.com/radistmorse/KSPPreciseManeuver/files/3026100/KSP.log)

**Comment by radistmorse** [comment]
According to the logs you did not install the mod correctly. You copied the source code of the mod, this is not how you should do it. Also, this is "precise maneuver" mod, not "precise guidance".

**Comment by gater308** [comment]
yes you are correct i mistyped guidance. it should have been precisemaneuver.
i downloaded and unzipped to my game data folder. should i have done different?
ty

**Comment by gater308** [comment]
now i get this.
![precisemaneuver](https://user-images.githubusercontent.com/49091113/55284395-6db0f400-533b-11e9-82ca-1b8f809e2605.png)

**Comment by gater308** [comment]
so I downloaded the zip file to my download folder. i then extracted to PreciseManeuver folder and placed that in my game data folder. i have done this with all mods and they work. i am sure it is on my end however i get the incompatible message. not sure the issue.
what should i look for. thank you

**Comment by radistmorse** [comment]
Just download the latest release (https://github.com/radistmorse/KSPPreciseManeuver/releases/latest/download/PreciseManeuver.zip) and unpack it to your gamedata folder. Do not clone or download the repository itself, it contains source code, not the compiled binary.
