### ISSUE TITLE
Can't type in dV amount textboxes.

### ISSUE THREAD

**Issue by Kibbick** [radistmorse/KSPPreciseManeuver#5]
I often need to type in the delta-v numbers, which I could do with PreciseNode, but can't with PreciseManeuver. I use this when I calculate or read out a value from another tool (delta-v map, transfer window planner, or w/e), or just know the burn is going to be huge, and don't want to click + 100 times...

**Comment by radistmorse** [comment]
That's because the textboxes are readonly.

I know it's a controversial change, but making the textboxes editable has both upsides and downsides. I went with uneditable. That may be the main difference between PN and PM. I have some ideas about making them editable, but not in the near future.

**Comment by Kibbick** [comment]
Yes, I understand this. I intended this as a feature request. Sorry I didn't make that clear, and no worries. It's your mod, and your choice - even if it's a deal breaker for me.
