### ISSUE TITLE
[Feature Request]: Analog to "plus orbit" from stock gizmo

### ISSUE THREAD

**Issue by NotTheEconomist** [radistmorse/KSPPreciseManeuver#6]
Would love to see a button to add an orbit period's amount of time to the maneuver, exactly as the stock gizmo does it. It's currently pretty difficult to advance a ton of time with any sort of granularity (even adjusting sensitivity down, I find myself either barely moving the node forward in time, or jumping 20 orbits into the future)

Currently I use PM's gizmo editor for everything EXCEPT this, where I have to click back over to the stick gizmo.

**Comment by kshenoy** [comment]
I second this.

**Comment by radistmorse** [comment]
done in 2.2
