### ISSUE TITLE
planned AP/PE distance not refreshed

### ISSUE THREAD

**Issue by d-faure** [radistmorse/KSPPreciseManeuver#7]
**Setup**
Define a maneuver node
Use the gizmo to define some new orbit definition
Right-click on the future AP/PE to have the distance+eta display stay while altering the orbit

**Bug**
When using the stock gizmo, the distance+eta display on the AP/PE ls refreshed according to node setup. (ok)
When using the plugin gizmo, the AP/PE distance and eta are refreshed on the plugin window, but not the AP/PE display itself. (ko)

**Comment by radistmorse** [comment]
It's a KSP bug. I reported it upstream, you can follow it here: http://bugs.kerbalspaceprogram.com/issues/13014
